#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# The MIT License (MIT)
#
# Copyright (c) 2023, Roland Rickborn (r_2@gmx.net)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# ---------------------------------------------------------------------------

import datetime as dt

import pytz

FILENAME = 'testfile'

HEADER_GOOD = 'Title,Url,Keywords,Match Similar Keywords,'\
    'State,Description,Reserved Keywords,Categories,'\
    'Start Date,End Date,Country/Region,Use AAD Location,'\
    'Groups,Device & OS,Targeted Variations,Last Modified,'\
    'Last Modified By,Id'
HEADER_BAD = 'Title,Url,Keywords,Match Similar Keywords,'\
    'State,Description,Reserved Keywords,Categories,'\
    'Start Date,End Date,Country/Region,Use AAD Location,'\
    'Groups,Device & OS,Targeted Variations,Last Modified,Id'

TITLE_GOOD = 'Test'
TITLE_BAD = 'Test Lorem ipsum dolor sit amet, consetetur sadipscing elitr'
URL_GOOD = 'http://test-rr.de'
URL_BAD = 'www.test-rr.de'
KEYWORDS_GOOD = 'test;testrr;test_rr'
KEYWORDS_BAD = 'test;testrr;test_rr;rtest1'
MATCH_SIMILAR_KEYWORDS_GOOD = 'true'
MATCH_SIMILAR_KEYWORDS_BAD = 'True'
STATE_GOOD = 'published'
STATE_BAD = 'Published'
DESCRIPTION = 'Das ist nur ein Test von Roland'
DESCRIPTION_BAD = 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr,'\
    'sed diam nonumy eirmod tempor invidunt ut labore et dolore magna'\
    'aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo'\
    'dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus'\
    'est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur'\
    'sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et'\
    'dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam'\
    'et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea'\
    'takimata sanctus est Lorem ipsum dolor sit amet.'
RESERVED_KEYWORDS_GOOD = 'rtest1;rtest2'
RESERVED_KEYWORDS_BAD = 'testrr'
CATEGORIES = 'Basic Category'
START_DATE = '2022-12-01T07:30:00+00'
START_DATE_BAD = 'Lorem ipsum'
END_DATE = '2022-12-29T07:30:00+00'
END_DATE_BAD = 'Lorem ipsum'
COUNTRY_GOOD = 'de;us'
COUNTRY_BAD = 'aa'
USE_AAD_LOCATION_FALSE_GOOD = 'False'
USE_AAD_LOCATION_FALSE_BAD = 'false'
USE_AAD_LOCATION_TRUE_GOOD = 'True'
USE_AAD_LOCATION_TRUE_BAD = 'true'
GROUPS_GOOD = 'd0dc8935-5cfb-47ae-bb41-3b362e6fee97;'\
    'd4f274a5-3f82-4165-a60d-f122a87dcdc3'
GROUPS_BAD = 'd0dc8935-5cfb-47ae-bb41-3b362e6fee9'
DEVICE_AND_OS_GOOD = 'pc-windows;pc-mac'
DEVICE_AND_OS_BAD = 'pc'

VAR_COUNTRY = 'it'
VARIATION_GOOD = '[{{"title":"{}","description":"{}","url":"{}",'\
    '"device":"{}","country":"{}"}}]'.format(
        TITLE_GOOD, DESCRIPTION, URL_GOOD, DEVICE_AND_OS_GOOD, VAR_COUNTRY)
VARIATION_BAD_1 = '[{{"title":"{}","description":"{}","url":"{}",'\
    '"device":"{}","country":"{}"}}]'.format(
        TITLE_GOOD, DESCRIPTION, URL_GOOD, DEVICE_AND_OS_GOOD, COUNTRY_BAD)
VARIATION_BAD_2 = '[{{"test":"{}","description":"{}","url":"{}",'\
    '"device":"{}","country":"{}"}}]'.format(
        TITLE_GOOD, DESCRIPTION, URL_GOOD, DEVICE_AND_OS_GOOD, VAR_COUNTRY)
VARIATION_BAD_3 = '[{{"title":"{}","description":"{}","url":"{}",'\
    '"device":"{}","country":"{}"}}]'.format(
        TITLE_BAD, DESCRIPTION, URL_GOOD, DEVICE_AND_OS_GOOD, VAR_COUNTRY)
VARIATION_BAD_4 = '[{{"title":"{}","description":"{}","url":"{}",'\
    '"device":"{}","country":"{}"}}]'.format(
        TITLE_GOOD, DESCRIPTION, URL_BAD, DEVICE_AND_OS_GOOD, VAR_COUNTRY)
VARIATION_BAD_5 = '[{{"title":"{}","description":"{}","url":"{}",'\
    '"device":"{}","country":"{}"}}]'.format(
        TITLE_GOOD, DESCRIPTION, URL_GOOD, DEVICE_AND_OS_BAD, VAR_COUNTRY)
VARIATION_BAD_6 = '[{{"title":"{}","description":"{}","url":"{}",'\
    '"device":"{}","country":"{}"}}]'.format(
        TITLE_GOOD, DESCRIPTION_BAD, URL_GOOD, DEVICE_AND_OS_GOOD, VAR_COUNTRY)

LAST_MODIFIED = '12/28/2022'
LAST_MODIFIED_BAD_1 = '12/12/2022'
LAST_MODIFIED_BAD_2 = 'Lorem ipsum'
LAST_MODIFIED_BY = 'usr@test.com'
ID_GOOD = 'dd8901da-7f6d-4c54-9251-a11a0ee48d52'
ID_BAD = '20a830b1-0729-4d97-9dfb-f9f7d93accc'

CSV_FILE_GOOD = '{}\n{},{},{},{},{},{},,,,{},,{},,,,{},{},{}'.format(
        HEADER_GOOD,
        TITLE_GOOD,
        URL_GOOD,
        KEYWORDS_GOOD,
        MATCH_SIMILAR_KEYWORDS_GOOD,
        STATE_GOOD,
        DESCRIPTION,
        END_DATE,
        USE_AAD_LOCATION_FALSE_GOOD,
        LAST_MODIFIED,
        LAST_MODIFIED_BY,
        ID_GOOD
    )
CSV_FILE_BAD = '{}\n{},{},{},{},{},{},,,,{},,{},,,,{},{},{}'.format(
        HEADER_GOOD,
        TITLE_BAD,
        URL_GOOD,
        KEYWORDS_GOOD,
        MATCH_SIMILAR_KEYWORDS_GOOD,
        STATE_GOOD,
        DESCRIPTION,
        END_DATE,
        USE_AAD_LOCATION_FALSE_GOOD,
        LAST_MODIFIED,
        LAST_MODIFIED_BY,
        ID_GOOD
    )

TEST_START_DATE = dt.datetime.utcnow().replace(tzinfo=pytz.UTC)
TEST_END_DATE = dt.datetime.utcnow().replace(tzinfo=pytz.UTC) + dt.timedelta(
    days=1)
TEST_LAST_MOD = dt.datetime.utcnow().replace(tzinfo=pytz.UTC) - dt.timedelta(
    days=1)

TEST_XLSX_FILE = [
    b'UEsDBBQABgAIAAAAIQBi7p1oXgEAAJAEAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBA',
    b'IooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACslMtOwzAQRf',
    b'dI/EPkLUrcskAINe2CxxIqUT7AxJPGqmNbnmlp/56J+xBCoRVqN7ESz9x7MvHNaLJubbaC',
    b'iMa7UgyLgcjAVV4bNy/Fx+wlvxcZknJaWe+gFBtAMRlfX41mmwCYcbfDUjRE4UFKrBpoFR',
    b'Y+gOOd2sdWEd/GuQyqWqg5yNvB4E5W3hE4yqnTEOPRE9RqaSl7XvPjLUkEiyJ73BZ2XqVQ',
    b'IVhTKWJSuXL6l0u+cyi4M9VgYwLeMIaQvQ7dzt8Gu743Hk00GrKpivSqWsaQayu/fFx8er',
    b'8ojov0UPq6NhVoXy1bnkCBIYLS2ABQa4u0Fq0ybs99xD8Vo0zL8MIg3fsl4RMcxN8bZLqe',
    b'j5BkThgibSzgpceeRE85NyqCfqfIybg4wE/tYxx8bqbRB+QERfj/FPYR6brzwEIQycAhJH',
    b'2H7eDI6Tt77NDlW4Pu8ZbpfzL+BgAA//8DAFBLAwQUAAYACAAAACEAtVUwI/QAAABMAgAA',
    b'CwAIAl9yZWxzLy5yZWxzIKIEAiigAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAKySTU/DMAyG70j8h8j31d2QEEJLd0FIuyFUfoBJ3A+1jaMkG92/JxwQVB',
    b'qDA0d/vX78ytvdPI3qyCH24jSsixIUOyO2d62Gl/pxdQcqJnKWRnGs4cQRdtX11faZR0p5',
    b'KHa9jyqruKihS8nfI0bT8USxEM8uVxoJE6UchhY9mYFaxk1Z3mL4rgHVQlPtrYawtzeg6p',
    b'PPm3/XlqbpDT+IOUzs0pkVyHNiZ9mufMhsIfX5GlVTaDlpsGKecjoieV9kbMDzRJu/E/18',
    b'LU6cyFIiNBL4Ms9HxyWg9X9atDTxy515xDcJw6vI8MmCix+o3gEAAP//AwBQSwMEFAAGAA',
    b'gAAAAhAI/vk3nmAgAApAYAAA8AAAB4bC93b3JrYm9vay54bWykVdtu4jAQfV9p/yFr8Rpy',
    b'AQKNCFXLRYu0XaF2274gIZMYYtWxs7YDVFX/fccJoVBeum0EtscDx2dmzjj9y13GrA2Rig',
    b'oeIa/pIovwWCSUryN0/2di95ClNOYJZoKTCD0ThS4H37/1t0I+LYV4sgCAqwilWueh46g4',
    b'JRlWTZETDp6VkBnWYMq1o3JJcKJSQnTGHN91AyfDlKMKIZQfwRCrFY3JSMRFRriuQCRhWA',
    b'N9ldJc1WhZ/BG4DMunIrdjkeUAsaSM6ucSFFlZHE7XXEi8ZBD2zutYOwmfAL6eC4NfnwSu',
    b's6MyGkuhxEo3AdqpSJ/F77mO552kYHeeg48htR1JNtTU8MBKBp9kFRywgjcwz/0ymgfSKr',
    b'USQvI+idY5cPPRoL+ijDxU0rVwnv/GmakUQxbDSo8TqkkSoS6YYktONmSRXxeUgdcPXD9A',
    b'zuAg55kEA2p/xTSRHGsyFFyD1PbUvyqrEnuYChCxdUv+FlQS6B2QEIQDI45DvFQzrFOrkC',
    b'xCw3B+ryDCuRQMenA+k2ItcZZBd8KabrCej4GezCVV5Bq60Qha3WCO10Q211TPFc5yRuZH',
    b'YsXnnfEfcsWxyZYDGaqiqNbvswXByLCW5ExLC9bT0S8oyx3eQJFACsm+h6dQBa+14LEMvc',
    b'XLuNuaTHpdz/aHraHdvhi79tXQ79nt7qTX6vptfzLuvEIwMghjgQud7utvoCPUhmKfuW7w',
    b'rvZ4bljQ5I3Gi7t/bDO/G2rfqwnY3HQPlGzVm1KMae0eKU/ENkK250NQz6fmtnQ+0kSnIL',
    b'ULtw0/qfZ+ErpOgbHX6ZlN6AjDLEInjEYVowk8thlOGDlHlMo7FaiVs8XLPqgKD5e3uW/L',
    b'JCNLhuYMOU28soj13xKyopwkpn8A5MjaQy12jGfNxYSanhhhjZdYEdNWMWZ3NTxEkdIkIe',
    b'YtggbV6T8aVw0vbNw2/L5zBAuaOT0ScOKZtMxkmLolu/oFM/gHAAD//wMAUEsDBBQABgAI',
    b'AAAAIQCBPpSX8wAAALoCAAAaAAgBeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHMgogQBKK',
    b'AAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsUk1L',
    b'xDAQvQv+hzB3m3YVEdl0LyLsVesPCMm0KdsmITN+9N8bKrpdWNZLLwNvhnnvzcd29zUO4g',
    b'MT9cErqIoSBHoTbO87BW/N880DCGLtrR6CRwUTEuzq66vtCw6acxO5PpLILJ4UOOb4KCUZ',
    b'h6OmIkT0udKGNGrOMHUyanPQHcpNWd7LtOSA+oRT7K2CtLe3IJopZuX/uUPb9gafgnkf0f',
    b'MZCUk8DXkA0ejUISv4wUX2CPK8/GZNec5rwaP6DOUcq0seqjU9fIZ0IIfIRx9/KZJz5aKZ',
    b'u1Xv4XRC+8opv9vyLMv072bkycfV3wAAAP//AwBQSwMEFAAGAAgAAAAhAH772fImAwAADg',
    b'gAABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWyck01vozAQhu+V+h8s34OBplGDgKpq',
    b'VW1vq+52ezZmCFb8wdrOl1b97x3IBirlEhWBMTPj552xh/x+rxXZgvPSmoImUUwJGGFraV',
    b'YFffv9PLujxAduaq6sgYIewNP78voq31m39i1AIEgwvqBtCF3GmBctaO4j24FBT2Od5gE/',
    b'3Yr5zgGvh0VasTSOF0xzaeiRkLlLGLZppIAnKzYaTDhCHCgeMH/fys6faFpcgtPcrTfdTF',
    b'jdIaKSSobDAKVEi+xlZazjlcK698mcC7J3eKf43JxkBvuZkpbCWW+bECGZHXM+L3/JloyL',
    b'kXRe/0WYZM4cbGV/gBMq/V5Kye3ISifYzTdhixHWb5fLNrIu6L/4/zXDd9IP8TScfB+0zG',
    b'uJJ9xXRRw0BX1IsteUsjIf+uePhJ3/MieBV79AgQiAGgklfXtW1q77wBc0xUj0Q0BP5CLI',
    b'LTyCUgVFKvF/B42jABsVynyan9Seh4b+6UjFPTxa9S7r0KIk/jg1NHyjwmRcRsk8XqS3o+',
    b'vV7n6AXLUBF6B1aJ6sPjyBF9jNmGWEwaz8BAAA//8AAAD//5TTWw6CMBAF0K2QLsDagoqm',
    b'kIj4fqE7IEjiFxpLfOzeogaYmf74R5hTAvcOSp/zvIzTMg3V7fJwbgETzNHXtNDmaiR85j',
    b'yFl2aj0yvOdZYXZcC6HdljocoqPK7054wZaHP3HnYVv4eKZz8RUSGgmFAhoYipcKGYUuFB',
    b'MaOiB8Wcij4UCyoGUCyp8KFYUTGEYm1JDIW6sRCU6tZCUKw7C0G57i0EBZtYCEr2YCEo2q',
    b'OFNNlys5v1gsq/FtToejUF6iKqHhUwt0Uk+roJOI+aittDiTqagiFqZwaGqJcNGKJGku87',
    b'S8bNT/aJhTf/8BsAAP//AAAA//+ySSwtyXfLzClJLVIoSk2zVXI0tAoyUlKoKLIqzUyxVa',
    b'o2gAJdIG0JIgwQBEyuVknfzqYgMT3VN7EoPTOvWCEnNa3EVslAz9xUSaEoMz0DzinJL7BV',
    b'MlRSSMovKcnPBTMzUhNTUotAqoGK0/LzgS6BcIBm6pfnF2UXZ6SmltgBAAAA//8DAFBLAw',
    b'QUAAYACAAAACEA6aYluGYGAABTGwAAEwAAAHhsL3RoZW1lL3RoZW1lMS54bWzsWc1uGzcQ',
    b'vhfoOxB7TyzZkmIZkQNLluI2cWLYSoocqV1qlxF3uSApO7oVybFAgaJp0UuB3noo2gZIgF',
    b'7Sp3Gbok2BvEKH5EpaWlRsJwb6Fx1sLffj/M9whrp67UHK0CERkvKsFVQvVwJEspBHNItb',
    b'wZ1+79J6gKTCWYQZz0grmBAZXNt8/72reEMlJCUI9mdyA7eCRKl8Y2VFhrCM5WWekwzeDb',
    b'lIsYJHEa9EAh8B3ZStrFYqjZUU0yxAGU6B7O3hkIYE9TXJYHNKvMvgMVNSL4RMHGjSxNlh',
    b'sNGoqhFyIjtMoEPMWgHwifhRnzxQAWJYKnjRCirmE6xsXl3BG8UmppbsLe3rmU+xr9gQjV',
    b'YNTxEPZkyrvVrzyvaMvgEwtYjrdrudbnVGzwBwGIKmVpYyzVpvvdqe0iyB7NdF2p1KvVJz',
    b'8SX6awsyN9vtdr1ZyGKJGpD9WlvAr1cata1VB29AFl9fwNfaW51Ow8EbkMU3FvC9K81Gzc',
    b'UbUMJoNlpAa4f2egX1GWTI2Y4Xvg7w9UoBn6MgGmbRpVkMeaaWxVqK73PRA4AGMqxohtQk',
    b'J0McQhR3cDoQFGsGeIPg0hu7FMqFJc0LyVDQXLWCD3MMGTGn9+r596+eP0Wvnj85fvjs+O',
    b'FPx48eHT/80dJyNu7gLC5vfPntZ39+/TH64+k3Lx9/4cfLMv7XHz755efP/UDIoLlEL758',
    b'8tuzJy+++vT37x574FsCD8rwPk2JRLfIEdrnKehmDONKTgbifDv6CabODpwAbQ/prkoc4K',
    b'0JZj5cm7jGuyugePiA18f3HVkPEjFW1MP5RpI6wF3OWZsLrwFuaF4lC/fHWexnLsZl3D7G',
    b'hz7eHZw5ru2Oc6ia06B0bN9JiCPmHsOZwjHJiEL6HR8R4tHuHqWOXXdpKLjkQ4XuUdTG1G',
    b'uSPh04gTTftENT8MvEpzO42rHN7l3U5syn9TY5dJGQEJh5hO8T5pjxOh4rnPpI9nHKyga/',
    b'iVXiE/JgIsIyrisVeDomjKNuRKT07bktQN+S029gqFdet++ySeoihaIjH82bmPMycpuPOg',
    b'lOc6/MNEvK2A/kCEIUoz2ufPBd7maIfgY/4Gypu+9S4rj79EJwh8aOSPMA0W/GoqjaTv1N',
    b'afa6YswoVON3xXh6Om3B0eRLiZ0TJXgZ7l9YeLfxONsjEOuLB8+7uvuu7gb/+bq7LJfPWm',
    b'3nBRaa5HlfbLrkdGmTPKSMHagJIzel6ZMlHBZRDxZNA2+muNnQlCfwtSjuDi4W2OxBgquP',
    b'qEoOEpxDj101I18sC9KxRDmXMNuZZTN8khO0zThJoc02k2Fdzwy2Hkisdnlkl9fKs+GMjJ',
    b'kUYzN/ThmtaQJnZbZ25e2YVa1US83mqlY1oplS56g2Uxl8uKgaLM6sCV0Igt4FrNyAEV3L',
    b'DrMJZiTSdrdz89QtmvWFukgmOCKFj7Teiz6qGidNY2UaRh4f6TnvFB+VuDU12bfgdhYnld',
    b'nVlrCbeu9tvDQdbude0nl7Ih1ZVk5OlqGjVtCsr9YDFOK8FQxhrIWvaQ5el7rxwyyGu6FQ',
    b'CRv2pyazCde5N5v+sKzCTYW1+4LCTh3IhVTbWCY2NMyrIgRYZoZwI/9qHcx6UQrYSH8DKd',
    b'bWIRj+NinAjq5ryXBIQlV2dmnF3FEYQFFK+VgRcZBER2jAxmIfg/t1qII+EZVwO2Eqgn6A',
    b'qzRtbfPKLc5F0pUvsAzOrmOWJ7gotzpFp5ls4SaPZzKYJyutEQ9088pulDu/KiblL0iVch',
    b'j/z1TR5wlcF6xF2gMh3OQKjHS+tgIuVMKhCuUJDXsCLrlM7YBogetYeA1BBffJ5r8gh/q/',
    b'zTlLw6Q1TH1qn8ZIUDiPVCII2YOyZKLvFGLV4uyyJFlByERUSVyZW7EH5JCwvq6BDX22By',
    b'iBUDfVpCgDBncy/tznIoMGsW5y/qmdj03m87YHujuwLZbdf8ZepFYq+qWjoOk9+0xPNSsH',
    b'rznYz3nU2oq1oPFq/cxHbQ6XPkj/gfOPipDZHyf0gdrn+1BbEfzWYNsrBFF9yTYeSBdIWx',
    b'4H0DjZRRtMmpRtWIru9sLbKLiRLjrdGV/I0jfpdM9p7Flz5rJzcvH13ef5jF1Y2LF1udP1',
    b'mBqS9mSK6vZoOsgYx5hftco/PPHBfXD0Nlzxj5mS9mr/AVzxwZRhfySA5LfONVs3/wIAAP',
    b'//AwBQSwMEFAAGAAgAAAAhAEJqH7gMAwAA1gcAAA0AAAB4bC9zdHlsZXMueG1spFVbb5sw',
    b'FH6ftP9g8U4MNLAkIlRLUqRK2zQpnbSHvjhgEqu+IGM6smn/fcdAEtLL2nV5CPbh+DuX7/',
    b'MhvmwER/dUV0zJueOPPAdRmamcye3c+XaTuhMHVYbInHAl6dzZ08q5TN6/iyuz53S9o9Qg',
    b'gJDV3NkZU84wrrIdFaQaqZJKeFMoLYiBrd7iqtSU5JU9JDgOPC/CgjDpdAgzkb0GRBB9V5',
    b'dupkRJDNswzsy+xXKQyGbXW6k02XBItfHHJEONH+kANfoQpLU+iiNYplWlCjMCXKyKgmX0',
    b'cbpTPMUkOyEB8tuQ/BB7wVntjX4j0hhres8sfU4Sy1qkwlQoU7U0QOfRhLo31zkYo9BBHS',
    b'tLlUOf8vx2JMTtaA8/Bycx7lGSuFDyBBZA3bajszupfsjUvuoiWK8krn6ie8LB4luMTHGl',
    b'kQElQIDWIomgnceScLbRzLoVRDC+78yBNbTi6f0EAyrbhLoI3f/Gep3Feh0y7o63jwoiM8',
    b'6PfQqgT9aQxCApQ7VMYYP69c2+hBokqL/LpfV7wXuryd4PwsEB3AZM4o3SOdy2IUOdKYk5',
    b'LQwUp9l2Z59GlfC/UcaAIpM4Z2SrJOGWoMOJfgHlZJTztb2R34sz7KYYMA932zbBisAuoZ',
    b'B+2eF1G4s/ROuwB7BjaNa/w6KmOOI/d9p/NqnjaUTKku+t+HpZnWH10n6pxAdoX2qxoTpt',
    b'59RTqK9q28MMobk9VttN6N+ApDOKjs1GVshzZ91OW53DdetbhjY144bJJwgC1Lw5Ue5ZxR',
    b'k7/loxHONACTktSM3NzfHl3DmtP9Oc1WJ69PrK7pVpIebOaf3JKtOPbAzamE8V3Hp4olqz',
    b'ufPravFhurpKA3fiLSbu+IKG7jRcrNxwvFysVunUC7zl78EQ/o8R3H4zQIT+eFZxGNS6L7',
    b'YvcX2yQTdPmy799k5C2sPcp0HkfQx9z00vPN8dR2TiTqKL0E1DP1hF48VVmIaD3MM3jmoP',
    b'+3439G3y4cwwQTmTB64ODA2tQBJs/1IEPjCBTx/k5A8AAAD//wMAUEsDBBQABgAIAAAAIQ',
    b'ALZ80GhAEAAFkDAAAUAAAAeGwvc2hhcmVkU3RyaW5ncy54bWx0U8tu2zAQvAfIPyx4yC2m',
    b'a6BFkEgKUqsuiiYo4EevASOtZQIUqe6u3Pjbeugn5RdKO0GQig4gUNDs7syQHGXXj62DLR',
    b'Lb4HP1YTRWgL4KtfVNrlbL2fmFAhbja+OCx1ztkNV1cXqSMQvEWc+52oh0l1pztcHW8Ch0',
    b'6GNlHag1Ej+p0dwRmpo3iNI6PRmPP+nWWK+gCr2XXE0+Kui9/dXj9BUoMrZFJsXTn7/xWV',
    b'pxmGkpMr2Hn0srckPoO+5+B6p5iN8ZqTawsK11huC9roUYSVRK5IpsJ/GEhqxzZKQt1u8S',
    b'TiNfE8hiYihKkUB5RO+Lr4/ih6OhnZ5jc8TKihFubkq4DZU5ZvUrhb5LXJS4tRXCmWm7K/',
    b'ixGO5vaahBifv7acgeaBOGWxODcBcDs7ZYD+f/K8Ln3bD+LZlYIsuwSyJ2tV+IDq97oqSF',
    b'+uTeuv7B2Zi5RKM0DDa69j0BWg97TdgGD/PgYtKH3DPjOCF/yfze1TnRqH7ToOOvUfwDAA',
    b'D//wMAUEsDBBQABgAIAAAAIQApdqu2TAEAAGgCAAARAAgBZG9jUHJvcHMvY29yZS54bWwg',
    b'ogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'CMkl1LwzAYhe8F/0PJfZt2HzpC24HKrhzInCjexeTdFtZ8kES7/nvTbqsdeiHkJjnnfTjn',
    b'Jfn8IKvoC6wTWhUoS1IUgWKaC7Ut0Mt6Ec9Q5DxVnFZaQYEacGheXl/lzBCmLTxZbcB6AS',
    b'4KJOUIMwXaeW8Ixo7tQFKXBIcK4kZbSX242i02lO3pFvAoTW+wBE859RS3wNj0RHRCctYj',
    b'zaetOgBnGCqQoLzDWZLhH68HK92fA50ycErhGxM6neIO2Zwdxd59cKI31nWd1OMuRsif4b',
    b'fl43NXNRaq3RUDVOacEWaBem3Ltr9pDlWOB4/tAivq/DLseiOA3zXlSldh0dFKsP2HtirH',
    b'vy0B27U4soFHIRc5tjgrr+P7h/UClaN0NI7TcLJ1dkumUzK5eW8TXMy3OY8P8pTj/8QZSS',
    b'cD4hlQdrkv/0b5DQAA//8DAFBLAwQUAAYACAAAACEAgZ0RL5QBAAAbAwAAEAAIAWRvY1By',
    b'b3BzL2FwcC54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    b'AAAAAAAAAAAAAAAACckkFu2zAQRfcFegeB+5hyWgSFQTEIkhZZtKgBK9nT1MgmSpEEZyLY',
    b'PU9v0ot1JCG2nHbV3cz80efjp9TtofNFDxldDJVYLkpRQLCxcWFXiaf6y9UnUSCZ0BgfA1',
    b'TiCChu9ft3ap1jgkwOsGCLgJXYE6WVlGj30BlcsBxYaWPuDHGbdzK2rbPwEO1LB4HkdVne',
    b'SDgQhAaaq3QyFJPjqqf/NW2iHfjwuT4mBtaqjmR87TrQpZLnRt2l5J01xLfX35zNEWNLxe',
    b'eDBa/kXFRMvQH7kh0dB495qzbWeLjnA3VrPIKS54F6BDOEuTYuo1Y9rXqwFHOB7ifHeS2K',
    b'rUEYMCvRm+xMIMYd1qZmrH1Cyvoub8ERbv3vX0SQleStSRnL+Qfz2n3Uy3GBi8vFwWCiYe',
    b'GSs3bkAb+3a5PpH9jLOfbIMEFPOGi65DmFN3zjvfmkN95fXfiBT6mOD4bgNcDLodrsTYaG',
    b'Mz8FfBqoR84u+8Hkfm/CDprXnb+F4bmfp39dL28W5YeSX3I2U/L8V+s/AAAA//8DAFBLAQ',
    b'ItABQABgAIAAAAIQBi7p1oXgEAAJAEAAATAAAAAAAAAAAAAAAAAAAAAABbQ29udGVudF9U',
    b'eXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhALVVMCP0AAAATAIAAAsAAAAAAAAAAAAAAAAAlw',
    b'MAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAI/vk3nmAgAApAYAAA8AAAAAAAAAAAAA',
    b'AAAAvAYAAHhsL3dvcmtib29rLnhtbFBLAQItABQABgAIAAAAIQCBPpSX8wAAALoCAAAaAA',
    b'AAAAAAAAAAAAAAAM8JAAB4bC9fcmVscy93b3JrYm9vay54bWwucmVsc1BLAQItABQABgAI',
    b'AAAAIQB++9nyJgMAAA4IAAAYAAAAAAAAAAAAAAAAAAIMAAB4bC93b3Jrc2hlZXRzL3NoZW',
    b'V0MS54bWxQSwECLQAUAAYACAAAACEA6aYluGYGAABTGwAAEwAAAAAAAAAAAAAAAABeDwAA',
    b'eGwvdGhlbWUvdGhlbWUxLnhtbFBLAQItABQABgAIAAAAIQBCah+4DAMAANYHAAANAAAAAA',
    b'AAAAAAAAAAAPUVAAB4bC9zdHlsZXMueG1sUEsBAi0AFAAGAAgAAAAhAAtnzQaEAQAAWQMA',
    b'ABQAAAAAAAAAAAAAAAAALBkAAHhsL3NoYXJlZFN0cmluZ3MueG1sUEsBAi0AFAAGAAgAAA',
    b'AhACl2q7ZMAQAAaAIAABEAAAAAAAAAAAAAAAAA4hoAAGRvY1Byb3BzL2NvcmUueG1sUEsB',
    b'Ai0AFAAGAAgAAAAhAIGdES+UAQAAGwMAABAAAAAAAAAAAAAAAAAAZR0AAGRvY1Byb3BzL2',
    b'FwcC54bWxQSwUGAAAAAAoACgCAAgAALyAAAAAA'
]
