name: 'Coverage'

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  coverage:
    runs-on: windows-latest

    steps:
      - name: Coverage Badge
        working-directory: ./coverage
        uses: tj-actions/coverage-badge-py@v1.8