name: 'Coverage'

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./coverage

    steps:
    - uses: actions/checkout@v3
    - name: Coverage Badge
      uses: tj-actions/coverage-badge-py@v1.8