name: 'Coverage'

on:
    pull_request:
        branches:
            - master
            - main

jobs:
    coverage:
        runs-on: windows-latest

        steps:
          - name: Get Cover 
            uses: orgoro/coverage@v3
            with:
                coverageFile: coverage/coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}